services:
  node:
    container_name: autonomys-node
    image: ghcr.io/autonomys/node:mainnet-2024-nov-06
    volumes:
      -  node-data-mainnet:/var/subspace:rw
    ports:
      - "9944:9944"
      - "9080:9080"
      - "0.0.0.0:30333:30333/tcp"
      - "0.0.0.0:30433:30433/tcp"
    restart: unless-stopped
    command:
      [
        "run",
        "--chain", "mainnet",
        "--base-path", "/var/subspace",
        "--rpc-cors", "all",
        "--rpc-methods", "unsafe",
        "--rpc-listen-on", "0.0.0.0:9944",
        "--prometheus-listen-on", "0.0.0.0:9080",
        "--farmer",
        "--name", "hakehardware tutorial"
      ]
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.100
    labels:
      com.spaceport.name: "Mainnet Node"
    environment:
      - TZ=America/Phoenix

  farmer:
    depends_on:
      node:
        condition: service_healthy
    container_name: autonomys-farmer
    image: ghcr.io/autonomys/farmer:mainnet-2024-nov-06
    volumes:
      - /z:/farm-1
      - /y:/farm-2
    ports:
      - "0.0.0.0:30533:30533/tcp"
    restart: unless-stopped
    command:
      [
        "farm",
        "--node-rpc-url", "ws://172.25.0.100:9944",
        "--listen-on", "/ip4/0.0.0.0/tcp/30533",
        "--reward-address", "sucFPpS5i65LRAPX1eJxgiLCN6KZS7LA4bSV57DpkuWYkrpkc",
        "--prometheus-listen-on", "0.0.0.0:9081",
        "path=/farm-1,size=125G",
        "path=/farm-2,size=125G"
      ]
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.101
    labels:
      com.spaceport.name: "Mainnet Farmer"
    environment:
      - TZ=America/Phoenix

networks:
  autonomys-network:
    external: true

volumes:
  node-data-mainnet: