services:
  node:
    container_name: autonomys_node
    image: ghcr.io/autonomys/node:gemini-3h-2024-oct-03 # Update to latest version
    volumes:
      -  node-data:/var/subspace:rw
    ports:
      - "9944:9944"
      - "9080:9080"
    restart: unless-stopped
    command:
      [
        "run",
        "--chain", "gemini-3h",
        "--base-path", "/var/subspace",
        "--rpc-cors", "all",
        "--rpc-methods", "unsafe",
        "--rpc-listen-on", "0.0.0.0:9944",
        "--prometheus-listen-on", "0.0.0.0:9080",
        "--farmer",
        "--name", "hakehardware"
      ]
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.100
    labels: # Optional for Space Port
      com.spaceport.name: "Milton Node"
    environment:
      - TZ=America/Phoenix

  nats:
    image: nats
    container_name: autonomys_nats
    restart: unless-stopped
    ports:
      - "4222:4222"
    volumes:
      - /home/hakehardware/autonomys/nats/nats.config:/nats.config:ro
    command: ["-c", "/nats.config"]
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.101
    labels:
      com.spaceport.name: "Milton NATs"

  cluster_controller:
    container_name: cluster_controller
    image: ghcr.io/autonomys/farmer:gemini-3h-2024-oct-03
    volumes:
      - /home/hakehardware/autonomys/controller:/controller
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "controller",
        "--base-path", "/controller",
        "--node-rpc-url", "ws://node:9944"
      ]
    labels:
      com.spaceport.name: "Milton Controller"
    environment:
      - TZ=America/Phoenix
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.102

  cluster_cache:
    container_name: cluster_cache
    image: ghcr.io/autonomys/farmer:gemini-3h-2024-oct-03
    volumes:
      - /home/hakehardware/autonomys/cache:/cache
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "cache",
        "path=/cache,size=110GB"
      ]
    labels:
      com.spaceport.name: "Milton Cache"
    environment:
      - TZ=America/Phoenix
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.103

  cluster_farmer:
    container_name: cluster_farmer
    image: ghcr.io/autonomys/farmer:gemini-3h-2024-oct-03
    volumes:
      - /media/autonomys/farm-80a3c:/farm-80a3c
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "farmer",
        "--reward-address", "YOUR REWARD ADDRESS",
        "path=/farm-80a3c,size=931G"
      ]
    environment:
      - TZ=America/Phoenix
    labels:
      com.spaceport.name: "Milton Farmer"
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.104

networks:
  autonomys-network:
    external: true

volumes:
  node-data:
