services:
  cluster_cache:
    container_name: cluster_cache
    image: ghcr.io/autonomys/farmer:<LATEST VERSION>
    restart: unless-stopped
    volumes:
      - /path/to/your/cache:/cache
    ports:
      - "9082:9082"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "--prometheus-listen-on", "0.0.0.0:9082",
        "cache",
        "path=/cache,size=<CACHE SIZE>"
      ]
    labels:
      com.spaceport.name: "Cache"
    environment:
      - TZ=<YOUR TIMEZONE>
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.103

networks:
  autonomys-network:
    external: true