services:
  cluster_controller:
    container_name: cluster_controller
    image: ghcr.io/autonomys/farmer:<LATEST VERSION>
    #platform: linux/amd64
    restart: unless-stopped
    volumes:
      - /path/to/your/controller:/controller
    ports:
      - "9081:9081"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "--prometheus-listen-on", "0.0.0.0:9081",
        "controller",
        "--base-path", "/controller",
        "--node-rpc-url", "ws://node:9944"
      ]
    labels:
      com.spaceport.name: "Controller"
    environment:
      - TZ=<YOUR TIMEZONE>
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.102

  cluster_cache:
    container_name: cluster_cache
    image: ghcr.io/autonomys/farmer:<LATEST VERSION>
    #platform: linux/amd64
    restart: unless-stopped
    volumes:
      - /path/to/your/cache:/cache
    ports:
      - "9082:9082"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "--prometheus-listen-on", "0.0.0.0:9082",
        "cache",
        "path=/cache,size=<CACHE SIZE>"
      ]
    labels:
      com.spaceport.name: "Cache"
    environment:
      - TZ=<YOUR TIMEZONE>
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.103
        
  cluster_farmer:
    container_name: cluster_farmer
    image: ghcr.io/autonomys/farmer:<LATEST VERSION>
    #platform: linux/amd64
    restart: unless-stopped
    volumes:
      - /path/to/your/farm-1:/farm-1
      - /path/to/your/farm-2:/farm-2
    ports:
      - "9083:9083"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "--prometheus-listen-on", "0.0.0.0:9083",
        "farmer",
        "--reward-address", "<YOUR REWARD ADDRESS>",
        "path=/farm-1,size=<YOUR SIZE>"
      ]
    environment:
      - TZ=<YOUR TIMEZONE>
    labels:
      com.spaceport.name: "Farmer"
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.104

  cluster_plotter:
    container_name: cluster_plotter
    image: ghcr.io/autonomys/farmer:<LATEST VERSION>
    #platform: linux/amd64
    restart: unless-stopped
    ports:
      - "9084:9084"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "--prometheus-listen-on", "0.0.0.0:9084",
        "plotter",
      ]
    environment:
      - TZ=<YOUR TIMEZONE>
    labels:
      com.spaceport.name: "GPU Plotter"
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.105
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

networks:
  autonomys-network:
    external: true
