services:
  cluster_farmer:
    container_name: cluster_farmer
    image: ghcr.io/autonomys/farmer:<LATEST VERSION>
    restart: unless-stopped
    volumes:
      - /path/to/your/farm-1:/farm-1
      - /path/to/your/farm-2:/farm-2
    ports:
      - "9083:9083"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "--prometheus-listen-on", "0.0.0.0:9083",
        "farmer",
        "--reward-address", "<YOUR REWARD ADDRESS>",
        "path=/farm-1,size=<YOUR SIZE>"
      ]
    environment:
      - TZ=<YOUR TIMEZONE>
    labels:
      com.spaceport.name: "Farmer"
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.104

networks:
  autonomys-network:
    external: true