services:

  nats:
    image: nats
    container_name: autonomys_nats
    restart: unless-stopped
    ports:
      - "4222:4222"
    volumes:
      - /home/hakehardware/autonomys_cluster/nats/nats.config:/nats.config:ro
    command: ["-c", "/nats.config"]
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.101
    labels:
      com.spaceport.name: "Bender NATs"

  farmer_controller:
    container_name: autonomys_controller
    image: ghcr.io/autonomys/farmer:gemini-3h-2024-sep-03 # Update to latest
    volumes:
      - /home/hakehardware/autonomys_cluster/controller:/controller
    command:
      [
        "cluster",
        "--nats-server", "nats://172.25.0.101:4222",
        "controller",
        "--base-path", "/controller",
        "--node-rpc-url", "ws://192.168.69.100:9944" # Update to Node IP
      ]
    labels:
      com.spaceport.name: "Bender Controller" # Optional - Update to Friendly Name
    environment:
      - TZ=America/Phoenix # Update to your TZ
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.102
      
  farmer_cache:
    container_name: autonomys_cache
    image: ghcr.io/autonomys/farmer:gemini-3h-2024-sep-03 # Update to latest
    volumes:
      - /home/hakehardware/autonomys_cluster/cache:/cache
    command:
      [
        "cluster",
        "--nats-server", "nats://172.25.0.101:4222",
        "cache",
        "path=/cache,size=100GB" # Minimum 100GB should be used
      ]
    labels:
      com.spaceport.name: "Bender Cache" # Optional - Update to Friendly Name
    environment:
      - TZ=America/Phoenix # Update to your TZ
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.103

  farmer:
    container_name: autonomys_farmer
    image: ghcr.io/autonomys/farmer:gemini-3h-2024-sep-03 # Update to latest
    volumes:
      - /media/autonomys/farm00:/farm00 # Update and Duplicate for your mount location
      - /media/autonomys/farm01:/farm01
    command:
      [
        "cluster",
        "--nats-server", "nats://172.25.0.101:4222",
        "farmer",
        "--reward-address", "YOUR REWARD ADDRESS", # Update with your reward address
        "path=/farm00,size=1.8T", # Update and duplicate path and size for each disk
        "path=/farm01,size=1.8T"
      ]
    environment:
      - TZ=America/Phoenix # Update to your TZ
    labels:
      com.spaceport.name: "Bender Farmer" # Optional - Update to Friendly Name
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.104

  farmer_plotter:
    container_name: autonomys_plotter
    image: ghcr.io/autonomys/farmer:gemini-3h-2024-sep-03 # Update to latest
    command:
      [
        "cluster",
        "--nats-server", "nats://172.25.0.101:4222",
        "plotter"
      ]
    environment:
      - TZ=America/Phoenix # Update to your TZ
    labels:
      com.spaceport.name: "Bender Plotter" # Optional - Update to Friendly Name
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.105

networks:
  autonomys-network:
    external: true