services:
  cluster_plotter:
    container_name: cluster_plotter
    image: ghcr.io/autonomys/farmer:<LATEST VERSION>
    restart: unless-stopped
    ports:
      - "9084:9084"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "--prometheus-listen-on", "0.0.0.0:9084",
        "plotter",
      ]
    environment:
      - TZ=<YOUR TIMEZONE>
    labels:
      com.spaceport.name: "GPU Plotter"
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.105
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

networks:
  autonomys-network:
    external: true