services:
  nats:
    image: nats
    container_name: nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "4248:4248"
    volumes:
      - /path/to/your/nats.config:/nats.config:ro
    command: [
        "-c", "/nats.config",
        "-cluster", "nats://0.0.0.0:4248",
        "--cluster_name", "cluster1"
        ]
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.101
    labels:
      com.spaceport.name: "NATs Seed Server"

networks:
  autonomys-network:
    external: true