services:
  node:
    container_name: autonomys_node
    image: ghcr.io/autonomys/node:<LATEST VERSION>
    #platform: linux/amd64
    volumes:
      -  node-data:/var/subspace:rw
    ports:
      - "0.0.0.0:30333:30333/tcp"
      - "0.0.0.0:30433:30433/tcp"
      - "9944:9944"
      - "9080:9080"
    restart: unless-stopped
    command:
      [
        "run",
        "--chain", "gemini-3h",
        "--base-path", "/var/subspace",
        "--listen-on", "/ip4/0.0.0.0/tcp/30333",
        "--dsn-listen-on", "/ip4/0.0.0.0/tcp/30433",
        "--rpc-cors", "all",
        "--rpc-methods", "unsafe",
        "--rpc-listen-on", "0.0.0.0:9944",
        "--prometheus-listen-on", "0.0.0.0:9080",
        "--farmer",
        "--name", "<YOUR NAME>"
      ]
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.100
    labels:
      com.spaceport.name: "Node 1"
    environment:
      - TZ=<YOUR TIMEZONE>

networks:
  autonomys-network:
    external: true

volumes:
  node-data: