# Autonomys cluster w/ GPU enabled where each component gets its own container 
services:
  cluster-controller:
    container_name: cluster-controller
    image: ghcr.io/autonomys/farmer:mainnet-2024-nov-05
    restart: unless-stopped
    volumes:
      - /home/hakehardware/autonomys/controller:/controller
    ports:
      - "9081:9081"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "--prometheus-listen-on", "0.0.0.0:9081",
        "controller",
        "--base-path", "/controller",
        "--node-rpc-url", "ws://node:9944"
      ]
    labels:
      com.spaceport.name: "Flexo Controller"
    environment:
      - TZ=America/Phoenix
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.102

  cluster-cache:
    container_name: cluster-cache
    image: ghcr.io/autonomys/farmer:mainnet-2024-nov-05
    restart: unless-stopped
    volumes:
      - /home/hakehardware/autonomys/cache:/cache
    ports:
      - "9082:9082"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "--prometheus-listen-on", "0.0.0.0:9082",
        "cache",
        "path=/cache,size=200GiB"
      ]
    labels:
      com.spaceport.name: "Flexo Cache"
    environment:
      - TZ=America/Phoenix
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.103

  cluster-plotter:
    container_name: cluster-plotter
    image: ghcr.io/autonomys/farmer:mainnet-2024-nov-05
    restart: unless-stopped
    ports:
      - "9084:9084"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "--prometheus-listen-on", "0.0.0.0:9084",
        "plotter"
      ]
    environment:
      - TZ=America/Phoenix
    labels:
      com.spaceport.name: "Flexo Plotter"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.105


  cluster-farmer:
    container_name: cluster-farmer
    image: ghcr.io/autonomys/farmer:mainnet-2024-nov-05
    #platform: linux/amd64
    restart: unless-stopped
    volumes:
      - /media/autonomys/farm-78440:/farm-78440 # Update with your path
    ports:
      - "9083:9083"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222", # Update to NATs IP
        "--prometheus-listen-on", "0.0.0.0:9083", # Optional Metrics
        "farmer",
        "--reward-address", "suei8oJGcc9vq2pqWfrKDAggPrUWyow5JhHgFrzRM8JbqWN19", # Update with your reward address
        "path=/farm-78440,size=929GiB", # Update with your path & size
      ]
    environment:
      - TZ=America/Phoenix # Update to Your TZ
    labels:
      com.spaceport.name: "Farmer Taurus"
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.104  

networks:
  autonomys-network:
    external: true
