# Dedicated Cluster Farmer
services:
  cluster-farmer:
    container_name: cluster-farmer
    image: ghcr.io/autonomys/farmer:mainnet-2024-nov-05
    #platform: linux/amd64
    restart: unless-stopped
    volumes:
      - /media/autonomys/farm-78440:/farm-78440 # Update with your path
    ports:
      - "9083:9083"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222", # Update to NATs IP
        "--prometheus-listen-on", "0.0.0.0:9083", # Optional Metrics
        "farmer",
        "--reward-address", "suei8oJGcc9vq2pqWfrKDAggPrUWyow5JhHgFrzRM8JbqWN19", # Update with your reward address
        "path=/farm-78440,size=929GiB", # Update with your path & size
      ]
    environment:
      - TZ=America/Phoenix # Update to Your TZ
    labels:
      com.spaceport.name: "Farmer"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.104  

networks:
  autonomys-network:
    external: true
