# Dedicated Cluster Cache
services:
  cluster-cache:
    container_name: cluster-cache
    image: ghcr.io/autonomys/farmer:mainnet-2024-nov-05
    restart: unless-stopped
    volumes:
      - /home/hakehardware/autonomys/cache:/cache
    ports:
      - "9082:9082"
    command:
      [
        "cluster",
        "--nats-server", "nats://nats:4222",
        "--prometheus-listen-on", "0.0.0.0:9082",
        "cache",
        "path=/cache,size=200GiB"
      ]
    labels:
      com.spaceport.name: "Flexo Cache"
    environment:
      - TZ=America/Phoenix
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.103

networks:
  autonomys-network:
    external: true
