services:
  prometheus: 
    image: prom/prometheus:latest
    container_name: prometheus
    command: "--config.file=/etc/prometheus/config.yaml"
    volumes:
      - </PATH/TO/CONFIG>/config.yaml:/etc/prometheus/config.yaml:ro
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      <NETWORK NAME>:
        ipv4_address: 172.20.0.10

volumes:
  prometheus_data:

networks:
  <NETWORK NAME>:
    external: true