# Autonomys Farmer No GPU
services:
  farmer:
    container_name: autonomys-farmer
    image: ghcr.io/autonomys/farmer:mainnet-2024-nov-06 # Update to Latest
    volumes:
      - /media/autonomys/farm-316de:/farm-316de # Update to Path of Farm
      - /media/autonomys/farm-91f5b:/farm-91f5b # Duplicate for each farm. Remove if only 1 farm exists
    ports:
      - "0.0.0.0:30533:30533/tcp"
    restart: unless-stopped
    command:
      [
        "farm",
        "--node-rpc-url", "ws://172.25.0.100:9944",
        "--listen-on", "/ip4/0.0.0.0/tcp/30533",
        "--reward-address", "sucFPpS5i65LRAPX1eJxgiLCN6KZS7LA4bSV57DpkuWYkrpkc", # Update
        "--prometheus-listen-on", "0.0.0.0:9081",
        "path=/farm-316de,size=126G", # Update to Path of Farm
        "path=/farm-91f5b,size=126G" # Duplicate for each farm. Remove if only 1 farm exists
      ]
    networks:
      autonomys-network:
        ipv4_address: 172.25.0.101
    labels:
      com.spaceport.name: "Farmer"
    environment:
      - TZ=America/Phoenix # Update

networks:
  autonomys-network:
    external: true