global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.20.0.10:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.20.0.1:9100']
        labels:
          instance: 'Milton'